blv.security.ai.api-key=${blv_security_ai_apiKey}

blv.security.ai.jwt-secret=${blv_security_ai_jwtSecret}


# Paths that only need the API Key (Public)
blv.security.ai.allow-paths=/api/v1/web_mall/virtual/product, \
                            /api/v1/web_mall/cells, \
                            /api/v1/web_mall/services/{cell_id}/intro, \
                            /api/v1/web_estudio/cell/{cell_id}/pricing

# Paths that REQUIRE OAuth 2.0 JWT (Sensitive)
blv.security.ai.auth-paths=/api/v1/team/joinedOases, \
                            /api/v1/team/member, \
                            /api/v1/team/acceptOasisInvitation, \
                            /api/v1/team/invite

blv.security.ai.valid-redirect-uris=https://coze.cn, https://tencent.com