blv.security.ai.api-key=${blv_security_ai_apiKey}

blv.security.ai.jwt-secret=${blv_security_ai_jwtSecret}


# Paths that only need the API Key (Public)
blv.security.ai.allow-paths=/api/v1/web_mall/virtual/product, \
                            /api/v1/web_mall/cells, \
                            /api/v1/web_mall/services/{cell_id}/intro, \
                            /api/v1/web_estudio/cell/{cell_id}/pricing

# Paths that REQUIRE OAuth 2.0 JWT (Sensitive)
blv.security.ai.auth-paths=/api/v1/team/joinedOases, \
                            /api/v1/team/member, \
                            /api/v1/team/acceptOasisInvitation, \
                            /api/v1/team/invite, \
                            /api/v1/team/dsp_case/list, \
                            /api/v1/team/oasis,/api/v1/team/talent, \
                            /api/v1/web_pod/me/proposal/order/query, \
                            /api/v1/web_epod/cell/plan_order, \
                            /api/v1/web_pod/virtual/order/list, \
                            /api/v1/ms/private/me/event/friend/list, \
                            /api/v1/ms/private/{friend}/event,/api/v1/ms/private/{friend}/event/storeText, \
                            /api/v1/web_estudio/discover/commercial_paper



blv.security.ai.valid-redirect-uris=https://coze.cn, https://tencent.com