blv.security.ai.api-key=${blv_security_ai_apiKey}

blv.security.ai.jwt-secret=${blv_security_ai_jwtSecret}


# Paths that only need the API Key (Public)
blv.security.ai.allow-paths=/api/v1/web_mall/virtual/product, \
                            /api/v1/web_mall/cells, \
                            /api/v1/web_mall/services/{cell_id}/intro, \
                            /api/v1/web_estudio/cell/{cell_id}/pricing

# Paths that REQUIRE OAuth 2.0 JWT (Sensitive)
blv.security.ai.auth-paths=/api/v1/team/joinedOases, \
                            /api/v1/team/member, \
                            /api/v1/team/acceptOasisInvitation, \
                            /api/v1/team/invite, \
                            /api/v1/team/dsp_case/list, \
                            /api/v1/team/oasis,/api/v1/team/talent, \
                            /api/v1/web_pod/me/proposal/order/query, \
                            /api/v1/web_epod/cell/plan_order, \
                            /api/v1/web_pod/virtual/order/list, \
                            /api/v1/ms/private/me/event/friend/list, \
                            /api/v1/ms/private/{friend}/event,/api/v1/ms/private/{friend}/event/storeText, \
                            /api/v1/web_estudio/discover/commercial_paper, \
                            /api/v1/team/discovery/commission,/api/v1/web_pod/discovery/cooperation/programs, \
                            /api/v1/web_estudio/cell/plan_order,/api/v1/web_estudio/brand/millstone/workflow, \
                            /api/v1/web_estudio/brand/commercial_paper,/api/v1/web_estudio/virtual/order/list, \
                            /api/v1/app/meetr/member/attendances,/api/v1/team/office/payroll/employee_query, \
                            /api/v1/web/affiliate/product,/api/v1/web/affiliate/choice_product, \
                            /api/v1/web/affiliate/outreach,/api/v1/team/trans, \
                            /api/v1/web_mall/brand/virtual/product,/api/v1/web_estudio/virtual/product/change_desc, \
                            /api/v1/web_estudio/services/intro/content/change,/api/v1/web_estudio/cell/plan, \
                            /api/v1/web_estudio/brand/cellIndices,/api/v1/web_estudio/cell/{cell_id}/profile



blv.security.ai.valid-redirect-uris=https://coze.cn, https://tencent.com